changelog:
  categories:
    - title: New Features
      labels:
        - "feature"
    - title: Bug Fixes
      labels:
        - "bug"
    - title: Documentation Improvements
      labels:
        - "documentation"
    - title: Performance Improvements
      labels:
        - "perf"
    - title: Code Refactoring
      labels:
        - "refactor"
    - title: Testing Changes
      labels:
        - "test"
    - title: Build Changes
      labels:
        - "dependencies"
    - title: Other Changes
      labels:
        - "*"
