[package]
name = "viking_macros"
version = "0.1.0"
edition = "2024"
licence = "MIT"
description = "Helpful macros"
repository = "https://github.com/Ozy-Viking/viking_macros"
readme = "./README.md"
keywords = ["macros", "enum"]

[dependencies]
