style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Ozy-Viking/viking_macros
options:
  sort: "semver"
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - test
        - doc
        - note
        - build
        - chore
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      test: Testing Changes
      doc: Documentation Improvements
      build: Build Changes
      note: Notes
      chore: Chores
  header:
    pattern: "^(?:(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s)?(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  merges:
    pattern: "^(?:.*\\(#(\\w+)\\))$"
    pattern_maps:
      - Source
  notes:
    keywords:
      - BREAKING CHANGE
      - Note
